language: node_js

sudo: false

node_js:
    - "4.2"
    - "4.1"
    - "4.0"
    - "0.12"
    - "0.11"
    - "0.10"

branches:
    only:
        - master
        - dev

install:
    - npm i istanbul
    - npm i

script: istanbul cover spec/run.js

after_success: codeclimate-test-reporter < coverage/lcov.info

addons:
    code_climate:
        repo_token: $CODECLIMATE_REPO_TOKEN

notifications:
    email: false
