language: node_js

sudo: false

node_js:
    - "4.2"
    - "4.1"
    - "4.0"
    - "0.12.7"
    - "0.11"
    - "0.10"

branches:
    only:
        - master
        - dev

install:
    - npm install codeclimate-test-reporter
    - npm i istanbul
    - npm i

script: istanbul cover spec/run.js

after_success:
    - echo $TRAVIS_NODE_VERSION
    - if [ "$TRAVIS_NODE_VERSION" == "v0.12.7" ]; codeclimate-test-reporter < ./coverage/lcov.info; fi

addons:
    code_climate:
        repo_token: aa4e3cdca1aa2e328f9b2031b761f3baa63fea94e0587ccba671e3d8b3ef9fda

notifications:
    email: false
