language: node_js

sudo: false

node_js:
    - "4.2"
    - "4.1"
    - "4.0"
    - "0.12.7"
    - "0.11"
    - "0.10"

branches:
    only:
        - master
        - dev

install:
    - npm install codeclimate-test-reporter
    - npm i istanbul
    - npm i

script: istanbul cover spec/run.js

after_success:
    - [ $TRAVIS_NODE_VERSION == 4.2 ] && "codeclimate-test-reporter" < ./coverage/lcov.info

notifications:
    email: false
