language: node_js

sudo: false

node_js:
    - "4.2"
    - "4.1"
    - "4.0"
    - "0.12"
    - "0.10"

branches:
    only:
        - master
        - dev

install:
    - npm i istanbul
    - npm i

script: istanbul cover spec/run.js

after_success: make sendc

notifications:
    email: false
